version: "3"

services:
  matrix_photos:
    build: .
    volumes:
      - ../:/workspace
      - ./data:/data
      # Docker socket to access Docker server
      - /var/run/docker.sock:/var/run/docker.sock
      # SSH directory
      - ~/.ssh:/home/vscode/.ssh
      - ~/.ssh:/root/.ssh
      # Git config
      - ~/.gitconfig:/home/districter/.gitconfig
      - ~/.gitconfig:/root/.gitconfig
    environment:
      - TZ=Europe/Berlin
    entrypoint: /bin/sh -c "while sleep 1000; do :; done"

  matrix_photos_db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db:/var/lib/postgresql/data

